name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      - name: build
        run: dotnet build -c Release

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      - name: test
        run: dotnet test
  publish:
    needs: [ build, test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          extra_plugins: |
            @semantic-release/git@7.0.18
            @semantic-release/exec@3.3.8
            @semantic-release/changelog@3.0.0
